A = [(1, 2, 3), (4, 5, 6)] # List A = 2 tuples of 3
print([*zip(*A)])  # [(1, 4), (2, 5), (3, 6)]
# zip(*A) == zip((1, 2, 3), (4, 5, 6)) passes each element of A as a seperate argument to zip()
# *zip to unpack the tuples generated by zip(*A) and constructs a list with these unpacked values

""" zip(*iterables, strict=False)
Iterate over several iterables in parallel, producing tuples with an item from each one.
To transpose a matrix is to turn rows into columns, and columns into rows.
'*' are used for unpacking iterables. (unpacking into function arguments)
 """